version: "3.9"

services:
  # 🐘 Laravel API
  api:
    build: ./api
    container_name: api
    ports:
      - "8000:8000"
    volumes:
      - ./api:/var/www/html
    environment:
      APP_ENV: local
      APP_DEBUG: true
      APP_KEY: base64:Etofvb/fNOoruzgWDJSLRSgbGV95CflqjeLEhy1EWG8=
      APP_URL: http://localhost:8000
      DB_CONNECTION: pgsql
      DB_HOST: postgres        # important: service name
      DB_PORT: 5432
      DB_DATABASE: technosystemdb
      DB_USERNAME: techuser
      DB_PASSWORD: techuser123
    depends_on:
      - postgres

  # ⚛️ React Web App
  web:
    build: ./web
    container_name: web
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    volumes:
      - ./web:/app
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://api:8000
      - VITE_API_KEY=your_api_key
      - VITE_ENV=development
    depends_on:
      - api

  # ⚛️ React Admin App
  admin:
    build: ./admin
    container_name: admin
    ports:
      - "3001:3000"
    stdin_open: true
    tty: true
    volumes:
      - ./admin:/app
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://api:8000
      - VITE_API_KEY=your_api_key
      - VITE_ENV=development
    depends_on:
      - api

  # 🐘 PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: techuser
      POSTGRES_PASSWORD: techuser123
      POSTGRES_DB: technosystemdb
    volumes:
      - pg_data:/var/lib/postgresql/data

  # 🧭 Optional: pgAdmin (nice UI for managing PostgreSQL)
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: unless-stopped
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - postgres

volumes:
  pg_data:

